apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-demo
  name: nginx-demo
  namespace: default
spec:
  ports:
    - port: 9080
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx-demo
  type: NodePort
